name: react-with-hooks-ci
on:
  push:
    branches:
      - Search-App-Maintenance
  pull_request:
    branches:
      - Search-App-Maintenance
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Packages
      run: npm install
    - name: Run unit tests
      run: npm test